import PackageDescription

// MARK: - You're free to change the `dependencies` array

let dependencies: [Package.Dependency] = [
    .Package(url: "https://github.com/mdab121/Flock.git", "0.4.1")
]

// MARK: - Below is autogenerated, *do not modify*

let package = Package(
   name: "Flockfile",
   dependencies: dependencies
)
